//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlak.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vlak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.IO.UnmanagedMemoryStream podobný System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream boom1 {
            get {
                return ResourceManager.GetStream("boom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap brana {
            get {
                object obj = ResourceManager.GetObject("brana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] brana1 {
            get {
                object obj = ResourceManager.GetObject("brana1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] diamond2 {
            get {
                object obj = ResourceManager.GetObject("diamond2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] emerald {
            get {
                object obj = ResourceManager.GetObject("emerald", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hranice {
            get {
                object obj = ResourceManager.GetObject("Hranice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] hranice1 {
            get {
                object obj = ResourceManager.GetObject("hranice1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] jablko {
            get {
                object obj = ResourceManager.GetObject("jablko", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] koruna {
            get {
                object obj = ResourceManager.GetObject("koruna", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] krizek {
            get {
                object obj = ResourceManager.GetObject("krizek", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Diamond
        ///9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9  
        ///9 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 9
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9  
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9 
        ///9 0 0 V 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 9   
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 9 
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 0 0 0  [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Kral
        ///9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9 
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9 
        ///9 0 0 0 0 0 0 2 0 2 0 2 0 2 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 2 2 2 2 2 2 2 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 2 2 2 2 2 2 2 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 2 2 2 2 2 2 2 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 9 9 9 9 9 9 9 9 9 0 0 0 0 0 9
        ///9 0 0 V 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9
        ///9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loadingscreen {
            get {
                object obj = ResourceManager.GetObject("loadingscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] minecraft {
            get {
                object obj = ResourceManager.GetObject("minecraft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap otevrenabrana {
            get {
                object obj = ResourceManager.GetObject("otevrenabrana", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] pozadi {
            get {
                object obj = ResourceManager.GetObject("pozadi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] redstone {
            get {
                object obj = ResourceManager.GetObject("redstone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] ryba {
            get {
                object obj = ResourceManager.GetObject("ryba", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.IO.UnmanagedMemoryStream podobný System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream seber {
            get {
                return ResourceManager.GetStream("seber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] strom {
            get {
                object obj = ResourceManager.GetObject("strom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] tresen {
            get {
                object obj = ResourceManager.GetObject("tresen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.IO.UnmanagedMemoryStream podobný System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream victory {
            get {
                return ResourceManager.GetStream("victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vlak {
            get {
                object obj = ResourceManager.GetObject("vlak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Byte[].
        /// </summary>
        public static byte[] vlak1 {
            get {
                object obj = ResourceManager.GetObject("vlak1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap znicenyvlak {
            get {
                object obj = ResourceManager.GetObject("znicenyvlak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
